# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "896a286da58f89dc29955edb4e84838b"
name = "Levi-bogo-discount"
handle = "levi-bogo-discount"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_cart_transforms,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
