# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0cd8e5be8cbaad78a5c2fa2a41a16a2b"
name = "Prashant-Discount-demo"
handle = "prashant-discount-demo"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_cart_transforms,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
